kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-{{ .Values.event_handler }}
spec:
  resources:
    requests:
      storage: 1Gi
  accessModes:
    - ReadOnlyMany
			    