kind: Service
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-irods-capability-automated-ingest-service
spec:
  selector:
    app: {{ .Release.Name }}-irods-capability-automated-ingest
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
  type: NodePort