apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-irods-capability-automated-ingest-deployment
  labels:
    app: {{ .Release.Name }}-irods-capability-automated-ingest
spec:
  replicas: 3
  selector:
    matchLabels:
      app: {{ .Release.Name }}-irods-capability-automated-ingest
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-irods-capability-automated-ingest
    spec:
      containers:
      - name: irods-capability-automated-ingest
        image: {{ .Values.docker.repo }}/irods_capability_automated_ingest:0.1.0
        ports:
        - containerPort: 5000
        env:
        - name: redis_host
          value: {{ .Release.Name }}-redis-master
        - name: FLASK_APP
          value: irods_capability_automated_ingest.flask_app
        - name: PYTHONPATH
          value: /event_handler
        - name: log_level
          value: {{ quote .Values.log_level }}
        volumeMounts:
        - name: event-handler
          mountPath: /event_handler
        command: ["flask"]
        args: ["run", "--host=0.0.0.0"]
      volumes:
      - name: event-handler
      	persistentVolumeClaim:
	  claimName: {{ .Values.event_handler }}
	  