apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-rq-deployment
  labels:
    app: rq
spec:
  replicas: 3
  selector:
    matchLabels:
      app: rq
  template:
    metadata:
      labels:
        app: rq
    spec:
      containers:
      - name: irods-rq
        image: {{ .Values.docker.repo }}/irods_rq:0.1.0
        env:
        - name: IRODS_HOST
          value: {{ quote .Values.IRODS_HOST }}
        - name: IRODS_PORT
          value: "{{ .Values.IRODS_PORT }}"
        - name: IRODS_USER_NAME
          value: {{ quote .Values.IRODS_USER_NAME }}
        - name: IRODS_ZONE_NAME
          value: {{ quote .Values.IRODS_ZONE_NAME }}
        - name: IRODS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: passwd
              key: irods
        - name: PYTHONPATH
          value: /event_handler
        volumeMounts:
        - name: data
          mountPath: /data
        - name: event-handler
          mountPath: /event_handler
        args: ["-u", "redis://{{ .Release.Name }}-redis-master:6379/0"]
      volumes:
      - name: data
        persistentVolumeClaim:
	  claimName: {{ .Values.data }}
      - name: event-handler
        persistentVolumeClaim:
	  claimName: {{ .Release.Name }}-{{ .Values.event_handler }}

