apiVersion: apps/v1
kind: Deployment
metadata:
  name: rq-deployment
  labels:
    app: rq
spec:
  replicas: 3
  selector:
    matchLabels:
      app: rq
  template:
    metadata:
      labels:
        app: rq
    spec:
      containers:
      - name: irods-rq
        image: irods_rq:0.1.0
        env:
        - name: IRODS_HOST
          value: "172.17.0.1"
        - name: IRODS_PORT
          value: "1247"
        - name: IRODS_USER_NAME
          value: rods
        - name: IRODS_ZONE_NAME
          value: tempZone
        - name: IRODS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: passwd
              key: irods
        volumeMounts:
        - name: data
          mountPath: /data
        - name: event-handler
          mountPath: /event_handler.py
        args: ["worker", "-u", "redis://{{ .Release.Name }}-redis-ha.default.svc.cluster.local:6379/0", "restart", "path", "file"]
      volumes:
      - name: data
        hostPath:
          path: /host/data
          type: Directory
      - name: event-handler
        hostPath:
          path: /host/event_handler.py
          type: File
