# Default values for chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

IRODS_HOST: irods-irods-service
IRODS_PORT: 1247
IRODS_USER_NAME: rods
IRODS_ZONE_NAME: tempZone
IRODS_PASSWORD: rods
event_handler: event-handler-pvc
data: data
log_level: WARN
docker:
  repo: zooh
redis:
  master:
    persistence:
      enabled: false
  usePassword: false
