apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-elasticsearch-deployment
  labels:
    app: {{ .Release.Name }}-elasticsearch
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-elasticsearch
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-elasticsearch
    spec:
      containers:
      - name: elasticsearch
        image: docker.elastic.co/elasticsearch/elasticsearch:6.2.4
        ports:
        - containerPort: 9200
        - containerPort: 9300


